### ISSUE TITLE
xlocalize matches directories

### ISSUE THREAD

**Issue by baracoder** [AGROSICA/node-localize#3]
xlocalize crashes, when I run it with a subdirectory called "js"

```
fs.js:476
  var r = binding.read(fd, buffer, offset, length, position);
                  ^
Error: EISDIR, illegal operation on a directory
    at Object.fs.readSync (fs.js:476:19)
    at Object.fs.readFileSync (fs.js:310:28)
    at processFile (/usr/lib/node_modules/localize/bin/xlocalize.js:119:24)
    at /usr/lib/node_modules/localize/bin/xlocalize.js:103:4
    at Array.forEach (native)
    at processDir (/usr/lib/node_modules/localize/bin/xlocalize.js:101:8)
    at Object.<anonymous> (/usr/lib/node_modules/localize/bin/xlocalize.js:144:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by dfellis** [comment]
Agrosica is no more, but this should be fixable. Let me fork this repo to my personal account and take a look.
